name: Save hello-world image

on:
  workflow_dispatch:

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull hello-world
        run: docker pull hello-world
      - name: Save as tar
        run: docker save hello-world -o hello-world.tar
      - name: Upload tar
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: hello-world.tar
